### PR TITLE
added updates from dev

### PR DESCRIPTION
**Pull request by hamilbrian**
added updates from dev, should be able to merge into master, delete all branches, and create a new dev branch from the updated master. Need at least 3 people to verify and approve changes. this has the new file structure. Also, if you can run the app in an emulator before approving, it would be helpful.

### CODE REVIEW

**Review by dodgeball01 — CHANGES_REQUESTED** [review]
Need to delete the AA_app folder and all content in the folder.  There are some files in both folders that will keep the app from running.

**Review by geo8103 — CHANGES_REQUESTED** [review]
what Brian said

**Comment by Sean6971** [comment]
Damn!!! It took long enough to close this!!! 2 years later?!?!?! bwahahahaha

**Comment by hamilbrian** [comment]
Yeah, I totally forgot about it. I almost never login to github directly.

**Pull request closed without merging**
